eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8083

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qq741831203/config-content.git
          username: qq741831203
          password: zhanghui0106
          searchPaths: '{profile}'
  application:
    name: config-server